- name: installing nginx package
  hosts: local
  connecting: local
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.package:
     name: nginx
     state: present

  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes




# condition uses in below like separate redhat or debian


# - name: install nginx if redhat
#     ansible.builtin.dnf:
#       name: nginx
#       state: present
#     when: ansible_os_family == "RedHat"

#   - name: install nginx if Debian
#     ansible.builtin.apt:
#       name: nginx
#       state: present
#     when: ansible_os_family == "Debian"     

