- name: installing nginx package
  hosts: local
  connecting: local
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.package:
     name: nginx
     state: present

  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes

