- name: vaiables in list
  hosts: server
  become: yes
  tasks:
  - name: print the vaiables
    ansible.builtin.debug:
     msg: "hi i am learing the course"
  - name: task level variables
    vars:
    course= aws
    duration= 10hours
    ansible.builtin.debug:
     msg: "hi i am learing {{ course}}, with the duration {{ duration }}"