- name: vaiables in list
  hosts: server
  become: yes

  vars:                     # play level variable declaration
   course: devops
   duration: 120 hours
   trainer: sivvu

  tasks:
  - name: print the vaiables
    ansible.builtin.debug:
     msg: "hi i am learing the course {{course}}, duration is {{duration}}, and the trainer is {{trainer}}"

  - name: task level variables  # task level variable declaration
    vars:
     course: aws
     duration: 10hours
     triner: sivvu
    ansible.builtin.debug:
     msg: "hi i am learing {{course}}, with the duration {{duration}} and trainer is {{trainer}}"

  


   

