- name: vaiables in list
  hosts: server
  become: yes

  vars:                     # play level variable declaration
   course: devops
   duration: 120 hours
   trainer: sivvu

  tasks:
  - name: print the vaiables
    ansible.builtin.debug:
     msg: "hi i am learing the course {{ course }}, duration is {{ duration }}, and the trainer is {{ trainer }}"

  - name: task level variables  # task level variable declaration
    vars:
     course: aws
     duration: 10hours
    ansible.builtin.debug:
     msg: "hi i am learing {{ course}}, with the duration {{ duration }}"

    vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false # not confidential
  - name: TRAINER
    prompt: Please enter the trainer name
    private: false # not confidential
  - name: DURATION
    prompt: Please enter the duration
    private: false # not confidential
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"


   

