- name: using prompt variable declaration
  hosts: server
  become: yes
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false # not confidential, if need confidential give "true"
  - name: TRAINER
    prompt: Please enter the trainer name
    private: false # not confidential, if need confidential give "true"
  - name: DURATION
    prompt: Please enter the duration
    private: false # not confidential, if need confidential give "true"
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ COURSE }}, Duration is: {{ DURATION }}, Trainer: {{ TRAINER }}"