- name: declared varibles from args
  hosts: server
  become: yes
  tasks:
  - name: print the variables
    ansible.builtin.debug:
     msg: "hi i am learning {{course}} and trainer is {{trainer}}"

# using "-e" we can give args

# like----->  -e "course=aws trainer=sivvu"

#ansible-playbook -i inventory.yml -e ansible_user=ec2-user -e ansible_password=DevOps321 05-args-var.yml -e "course=aws trainer=sivvu"
    