# - name: declared varibles from args
#   hosts: server
#   become: yes
#   tasks:
#   - name: print the variables
#     ansible.builtin.debug:
#      msg: "hi i am learning {{course}} and trainer is {{trainer}}"

- name: variables to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hello {{NAME}}, Good {{GREETING}}"     