- name: data types in ansible
  hosts: local
  connection: local
  vars:
    course: aws
    duration: 100 hours
    topics:
      - linux: linux commands   #with in list again mapping
        copy: cp
        move: mv
        create: touch and mkdir
        remove: rm
      - shell
      - ansible
      - terraform
      # topic:
      # - devops
      # - security group # here we can not give in list inside list
    level: true
  tasks:
  - name: print the data types
    ansible.builtin.debug:
      msg: "hi i am learing course {{course}} and topics {{topics}} and level {{level}} with the duration {{duration}}"