- name: conditions using in ansible
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false     # you can see the number in prompt, when you entered
  # vars:
  #  number: 140
  tasks:
  - name: print the number is less than 10 
    ansible.builtin.debug:
      msg: "given number {{number}} is less than 10"
    #when: number < 10                         ---- this in play or task level used
    when: number | int < 10                # this for prompt level so need to use pipe because it is convet to int, before that takes as a string

  - name: print the number is greater than 10    
    ansible.builtin.debug:
      msg: "given number {{number}} is greater than 10"  
    #when: number >= 10
    when: number | int >= 10



# - name: create user
#   hosts: web
#   become: yes
#   tasks:
#   - name: check user exist or not
#     ansible.builtin.command: id expense
#     register: USER #here USER is a variable that gets output from above command
#     ignore_errors: True

#   - name: print the user information
#     ansible.builtin.debug:
#       msg: "user info: {{ USER }}"

#   - name: create user
#     ansible.builtin.command: useradd expense
#     when: USER.rc != 0    