- name: loopes using in ansible
  hosts: server
  become: yes
  #connection: local
  tasks:
  - name: installing packages      # here installing packages
    ansible.builtin.package:
      #msg: "installing package"
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    - postfix  

  - name: removing packages        # hereswe can remove or install process how it works like
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'nginx', state: 'absent' } 
    - { name: 'mysql', state: 'present' } 
    - { name: 'postfix', state: 'present' } 