- name: loopes using in ansible
  hosts: server
  become: yes
  #connection: local
  tasks:
  - name: installing 
    ansible.builtin.packages:
      #msg: "installing packages"
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    - postfix  