- name: loopes using in ansible
  hosts: server
  become: yes
  #connection: local
  tasks:
  - name: print names
    ansible.builtin.packages:
      #msg: "installing package"
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    - postfix  