- name: filerters using in ansible
  hosts: local
  connection: local
  tasks:
  - name: print the filter value
    ansible.builtin.debug:
      msg: "hello {{course | default ('good morning')}}"

  - name : print the upper case
    ansible.builtin.debug:
      msg: "hello {{course | default ('good morning') | upper}}"

  - name : print the lower case
    ansible.builtin.debug:
      msg: "hello {{course | default ('good morning') | lower}}"

  - name : print the unique set value
    vars:
     numbres1: [1, 2, 5, 1, 3, 4, 10]
    ansible.builtin.debug:
      msg: "{{numbres1 | unique}}"

  - name: print the union of sets value
    vars:
      numbres1: [1, 2, 5, 1, 3, 4, 10]
      numbres2: [1, 2, 3, 4, 5, 11, 99]
    ansible.builtin.debug:
     msg: "{{numbres1 | union(numbres2)}}"  

  - name: print the intersects of sets value
    vars:
      numbres1: [1, 2, 5, 1, 3, 4, 10]
      numbres2: [1, 2, 3, 4, 5, 11, 99]
    ansible.builtin.debug:
      msg: "{{ numbres1 | intersect(numbres2) }}"

  - name : print the minimum and maximum value
    vars:
     numbres1: [1, 2, 5, 1, 3, 4, 10]
    ansible.builtin.debug:
      msg: "min: {{numbres1 | min}}, max: {{numbres1 | max}}"